# Generated by Django 3.0.8 on 2020-08-12 03:37

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=stdimage.models.JPEGField(upload_to='photos'),
        ),
    ]
