# Generated by Django 3.0.8 on 2020-08-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20200815_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(upload_to='path/to/img'),
        ),
    ]
